app/controllers/contas_controller.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import current_user, login_required
from app import db
from app.models.users_model import User
from app.models.contas_model import Conta
from app.models.transacoes_model import Transacao
from datetime import datetime

contas_bp = Blueprint('contas', __name__)


@contas_bp.route('/criar/<int:user_id>', methods=['GET', 'POST'])
@login_required
def criar_conta(user_id):
    if request.method == 'POST':
        nome = request.form['nome'] 
        instituicao_bancaria = request.form.get('instituicao_bancaria') # Se o campo for nulo, o get retorna None
        descricao = request.form.get('descricao')
        tipo_conta = request.form.get('tipo_conta')
        
        nova_conta = Conta(nome=nome, instituicao_bancaria=instituicao_bancaria, descricao=descricao, tipo_conta=tipo_conta, user_id=user_id)
        db.session.add(nova_conta) 
        db.session.commit()

        return redirect(url_for('contas.ver_contas', user_id=user_id))

    return render_template('criar_conta.html', user_id=user_id)


@contas_bp.route('/update/<int:conta_id>', methods=['GET', 'POST'])
@login_required
def update(conta_id):
    conta = Conta.query.get(conta_id)

    if not conta:
        return "Conta não encontrada", 404

    if conta.user_id != current_user.id:
        return "Acesso não autorizado", 403

    if request.method == 'POST':
        nome = request.form.get('nome')
        instituicao = request.form.get('instituicao_bancaria')
        descricao = request.form.get('descricao')
        tipo_conta = request.form.get('tipo_conta')

        if nome and nome != conta.nome:
            conta.nome = nome
        if instituicao and instituicao != conta.instituicao_bancaria:
            conta.instituicao_bancaria = instituicao
        if descricao and descricao != conta.descricao:
            conta.descricao = descricao
        if tipo_conta and tipo_conta != conta.tipo_conta:
            conta.tipo_conta = tipo_conta

        try:
            db.session.commit()
        except Exception as e:
            db.session.rollback()
            return f"Erro ao atualizar conta: {str(e)}", 500

        return redirect(url_for('contas.ver_contas', user_id=conta.user_id))
    
    return render_template('dashboard.html', conta=conta)


@contas_bp.route('/<int:user_id>/contas')
@login_required
def ver_contas(user_id):
    user = User.query.get(user_id)
    transacoes = Transacao.query.all()
    if user:
        contas = user.contas
        saldo_total = sum(conta.saldo for conta in contas)  
        return render_template('ver_contas.html', contas=contas, user=current_user, saldo_total=saldo_total, transacoes=transacoes)
    return "User not found", 404


@contas_bp.route('/<int:user_id>/conta/<int:conta_id>')
@login_required
def detalhe_conta(user_id, conta_id):
    user = User.query.get(user_id)
    conta = Conta.query.get(conta_id)
    if conta:
        return render_template('detalhe_conta.html', conta=conta, user_id=user_id, conta_id=conta_id, user=user)


@contas_bp.route('/<int:conta_id>/depositar', methods=['POST'])
@login_required
def depositar(conta_id):
    conta = Conta.query.get(conta_id)
    if conta.user_id != current_user.id:
        return "Acesso não autorizado", 403
    
    data = datetime.strptime(request.form.get('data'), '%Y-%m-%d') # Convertendo para datetime
    descricao = request.form.get('descricao')
    if conta:
        valor = float(request.form['valor'])
        try:
            conta.depositar(valor, data, descricao)
            return redirect(url_for('contas.ver_contas', user_id=conta.user_id)) # trocar a rota
        except ValueError as e:
            return str(e), 400 # Criar template dinamica para erros
    return 'Conta não encontrada', 404


@contas_bp.route('/<int:conta_id>/sacar', methods=['POST'])
@login_required
def sacar(conta_id):
    conta = Conta.query.get(conta_id)
    if conta.user_id != current_user.id:
        return "Acesso não autorizado", 403

    if conta:
        valor = float(request.form['valor'])
        data = datetime.strptime(request.form.get('data'), '%Y-%m-%d') # Convertendo para datetime
        descricao = request.form.get('descricao')
        try:
            conta.sacar(valor, data, descricao)
            return redirect(url_for('contas.ver_contas', user_id=conta.user_id)) # trocar a rota
        except ValueError as e:
            return str(e), 400
    return "Conta não encontrada", 404


@contas_bp.route('<int:user_id>/conta/<int:conta_id>/extrato', methods=["GET"])
@login_required
def ver_extrato(user_id, conta_id):
    user = User.query.get(user_id)
    conta = Conta.query.get(conta_id)

    if conta and conta.user_id == user.id:
        transacoes = Transacao.query.filter_by(conta_id=conta.id).all()
        return render_template('extrato_conta.html', transacoes=transacoes, conta=conta, user=user)
    
    return redirect(url_for('contas.ver_contas', user_id=user.id))


@contas_bp.route('<int:user_id>/conta/<int:conta_id>/delete', methods=['POST'])
@login_required
def delete(user_id, conta_id):
    user = User.query.get(user_id)
    conta = Conta.query.get(conta_id)

    if not user or not conta or conta.user_id != current_user.id:
        return "Acesso não autorizado ou conta inexistente", 403

    try:
        # Deletar transações da conta
        transacoes = Transacao.query.filter_by(conta_id=conta.id).all()
        for transacao in transacoes:
            db.session.delete(transacao)

        # Deletar conta
        db.session.delete(conta)
        db.session.commit()

        return redirect(url_for('contas.ver_contas', user_id=user.id))
    except Exception as e:
        db.session.rollback()
        return f"Erro ao deletar conta: {str(e)}", 500
    

@contas_bp.route('<int:conta_id>/transacao/delete/<int:transacao_id>', methods=['POST'])
@login_required
def delete_transacao(transacao_id, conta_id):
    transacao = Transacao.query.get(transacao_id)

    if not transacao or transacao.conta_id != conta_id:
        return "Transação não encontrada ou conta incorreta", 404

    conta = transacao.conta

    # Verifica se a conta pertence ao usuário logado
    if conta.user_id != current_user.id:
        return "Acesso não autorizado", 403

    try:
        # Reverte o saldo
        if transacao.natureza == 'saque':
            conta._saldo += transacao.valor
        elif transacao.natureza == 'deposito':
            conta._saldo -= transacao.valor

        db.session.delete(transacao)
        db.session.commit()

        return redirect(url_for('contas.ver_extrato', conta_id=conta_id, user_id=current_user.id))

    except Exception as e:
        db.session.rollback()
        return f"Erro ao deletar transação: {str(e)}", 500

app/templates/criar_conta.html
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Draco | Nova Conta</title>
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/criar_conta.css') }}"
    />
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
      rel="stylesheet"
    />
    <link
      rel="icon"
      type="image/x-icon"
      href="{{ url_for('static', filename='assets/favico.png') }}"
    />
  </head>
  <body>
    <div class="container">
      <!-- Botão de Voltar -->
      <div class="top-bar">
        <a
          href="{{ url_for('contas.ver_contas', user_id=user_id) }}"
          class="btn-voltar"
        >
          <i class="fas fa-arrow-left"></i> Voltar
        </a>
      </div>

      <h1>Criar Conta</h1>
      <form method="POST">
        <label for="nome">Nome da Conta</label>
        <input type="text" id="nome" name="nome" required />

        <label for="instituicao_bancaria">Instituição Bancária</label>
        <select id="instituicao_bancaria" name="instituicao_bancaria" required>
          <option value="Banco Inter">Banco Inter</option>
          <option value="Nubank">Nubank</option>
          <option value="Banco do Brasil">Banco do Brasil</option>
          <option value="Bradesco">Bradesco</option>
          <option value="Caixa">Caixa</option>
          <option value="Itau">Itaú</option>
          <option value="Santander">Santander</option>
        </select>

        <label for="descricao">Descrição</label>
        <input type="text" id="descricao" name="descricao" required />

        <label for="tipo_conta">Tipo de Conta</label>
        <select id="tipo_conta" name="tipo_conta" required>
          <option value="Conta corrente">Conta Corrente</option>
          <option value="Carteira">Carteira</option>
          <option value="Poupança">Poupança</option>
          <option value="Investimentos">Investimentos</option>
          <option value="Outros">Outros</option>
        </select>

        <input type="hidden" name="user_id" value="{{ user_id }}" />

        <button type="submit" class="btn-criar">Criar Conta</button>
      </form>
    </div>
  </body>
</html>

app/templates/dashboard.html
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Draco | Dashboard</title>
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/dashboard.css') }}"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
    />
    <link
      rel="icon"
      type="image/x-icon"
      href="{{ url_for('static', filename='assets/favico.png') }}"
    />
  </head>
  <body>
    <div class="dashboard-container">
      <div class="dashboard-header">
        <h1>Bem-vindo, {{ user.name }}</h1>
        <p>Este é o seu painel de controle.</p>
      </div>

      <div class="card-container">
        <div class="card">
          <i class="fas fa-wallet"></i>
          <h3>Suas Contas</h3>
          <p>Gerencie suas contas e despesas.</p>
          <a href="{{ url_for('contas.ver_contas', user_id=user.id) }}"
            >Ver Contas</a
          >
        </div>

        <div class="card">
          <i class="fas fa-user-circle"></i>
          <h3>Seu Perfil</h3>
          <p>Atualize suas informações pessoais.</p>
          <a href="{{ url_for('ver_perfil', user_id=user.id) }}">Ver Perfil</a>
        </div>

        <div class="card">
          <i class="fas fa-sign-out-alt"></i>
          <h3>Sair</h3>
          <p>Encerrar sua sessão.</p>
          <a href="{{ url_for('logout') }}">Logout</a>
        </div>
      </div>
    </div>
  </body>
</html>

app/templates/detalhe_conta.html
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Draco | Conta</title>
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/detalhe_conta.css') }}"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
    />
    <link
      rel="icon"
      type="image/x-icon"
      href="{{ url_for('static', filename='assets/favico.png') }}"
    />
  </head>
  <body>
    <div class="dashboard-container">
      <!-- Botão de Voltar -->
      <div class="top-bar">
        <a href="{{ url_for('contas.ver_contas', user_id=user_id) }}" class="btn-voltar">
          <i class="fas fa-arrow-left"></i> Voltar
        </a>
      </div>

      <div class="saldo-container">
        <div class="saldo-circle">
          <span>R${{ "{:.2f}".format(conta.saldo) }}</span>

        </div>
      </div>

      <h1>Detalhes de {{ conta.nome }}</h1>

      <form class="form" method="POST" action="{{ url_for('contas.update', conta_id=conta.id) }}">
        <div class="form-row">
          <label for="nome">Nome da Conta</label>
          <input type="text" id="nome" name="nome" value="{{ conta.nome }}" required />
        </div>

        <div class="form-row">
          <label for="instituicao_bancaria">Instituição Bancária</label>
          <select id="instituicao_bancaria" name="instituicao_bancaria" required>
            <option value="Banco Inter" {% if conta.instituicao_bancaria == "Banco Inter" %}selected{% endif %}>
              Banco Inter
            </option>
            <option value="Nubank" {% if conta.instituicao_bancaria == "Nubank" %}selected{% endif %}>
              Nubank
            </option>
            <option value="Banco do Brasil" {% if conta.instituicao_bancaria == "Banco do Brasil" %}selected{% endif %}>
              Banco do Brasil
            </option>
            <option value="Bradesco" {% if conta.instituicao_bancaria == "Bradesco" %}selected{% endif %}>
              Bradesco
            </option>
            <option value="Caixa" {% if conta.instituicao_bancaria == "Caixa" %}selected{% endif %}>
              Caixa
            </option>
            <option value="Itau" {% if conta.instituicao_bancaria == "Itau" %}selected{% endif %}>
              Itaú
            </option>
            <option value="Santander" {% if conta.instituicao_bancaria == "Santander" %}selected{% endif %}>
              Santander
            </option>
          </select>
        </div>

        <div class="form-row">
          <label for="descricao">Descrição</label>
          <input type="text" id="descricao" name="descricao" value="{{ conta.descricao }}" required />
        </div>

        <div class="form-row">
          <label for="tipo_conta">Tipo de Conta</label>
          <select id="tipo_conta" name="tipo_conta" required>
            <option value="Conta corrente" {% if conta.tipo_conta == "Conta corrente" %}selected{% endif %}>
              Conta Corrente
            </option>
            <option value="Carteira" {% if conta.tipo_conta == "Carteira" %}selected{% endif %}>
              Carteira
            </option>
            <option value="Poupança" {% if conta.tipo_conta == "Poupança" %}selected{% endif %}>
              Poupança
            </option>
            <option value="Investimentos" {% if conta.tipo_conta == "Investimentos" %}selected{% endif %}>
              Investimentos
            </option>
            <option value="Outros" {% if conta.tipo_conta == "Outros" %}selected{% endif %}>
              Outros
            </option>
          </select>
        </div>

        <input type="hidden" name="user_id" value="{{ user_id }}" />

        <button type="submit" class="save-button">Salvar Alterações</button>
      </form>
      <form action="{{ url_for('contas.delete', user_id=current_user.id, conta_id=conta.id) }}" method="POST">
        <button type="submit" class="delete-btn">
          Excluir Conta
        </button>
      </form>

      <!-- Botões para ações adicionais -->
      <div class="action-buttons">
        <form action="{{ url_for('contas.ver_extrato', user_id=current_user.id, conta_id=conta.id) }}">
        <button id="ver-extrato-btn" class="ver-extrato-btn">
          <i class="fa-solid fa-list"></i> Ver extrato
        </button>
      </form>
        <button id="new-transaction-btn" class="new-transaction-btn">
          <i class="fas fa-plus"></i> Nova Transação
        </button>
      </div>
      
    </div>
    

    <!-- Modal para Nova Transação -->
    <div id="transaction-modal" class="modal">
      <div class="modal-content">
        <span class="close">&times;</span>
        <h2>Nova Transação</h2>
        <form method="POST" id="transaction-form" action="/contas/{{ conta_id }}/sacar" data-conta-id="{{ conta_id }}">
          <div class="form-row">
            <label for="natureza">Natureza</label>
            <select id="natureza" name="natureza" required>
              <option value="Saque">Saque</option>
              <option value="Deposito">Depósito</option>
            </select>
          </div>
          <div class="form-row">
            <label for="valor">Valor</label>
            <input type="number" id="valor" name="valor" step="0.01" required />
          </div>
          <div class="form-row">
            <label for="data">Data</label>
            <input type="date" id="data" name="data" required />
          </div>
          <div class="form-row">
            <label for="descricao">Descrição</label>
            <input type="text" id="descricao" name="descricao" required />
          </div>
          <button type="submit" class="save-button">Salvar Transação</button>
        </form>
        
      </div>
    </div>

    <script src="{{ url_for('static', filename='js/detalhe_conta.js') }}"></script>
  </body>
</html>

app/templates/extrato_conta.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Draco | Extrato</title>
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/extrato_conta.css') }}"
    />
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
      rel="stylesheet"
    />
    <link
      rel="icon"
      type="image/x-icon"
      href="{{ url_for('static', filename='assets/favico.png') }}"
    />
  </head>
  <body>
    <div class="transactions-container">
      <!-- Botão de Voltar -->
      <div class="top-bar">
        <a
          href="{{ url_for('contas.detalhe_conta', user_id=current_user.id, conta_id=conta.id) }}"
          class="btn-voltar"
        >
          <i class="fas fa-arrow-left"></i> Voltar
        </a>
      </div>
      <div class="transactions-card">
        <h1>Transações de {{ conta.nome }}</h1>
        <table class="transactions-table">
          <thead>
            <tr>
              <th>Natureza</th>
              <th>Valor</th>
              <th>Data</th>
              <th>Descrição</th>
              <!-- Nova coluna de Descrição -->
              <th>Ações</th>
            </tr>
          </thead>
          <tbody>
            {% for transacao in transacoes %}
            <tr>
              <td>{{ transacao.natureza }}</td>
              <td>{{ "%.2f"|format(transacao.valor) }}</td>
              <td>{{ transacao.data.strftime('%d/%m/%Y %H:%M') }}</td>
              <td>{{ transacao.descricao or 'Não especificada' }}</td>
              <!-- Exibindo a descrição da transação -->
              <td>
                <div class="actions">
                  <form
                    action="{{ url_for('contas.delete_transacao',user_id = user.id, conta_id=conta.id, transacao_id=transacao.id) }}"
                    method="POST"
                    class="delete-form"
                  >
                    <button type="submit" class="btn-action delete">
                      <i class="fas fa-trash-alt"></i>
                    </button>
                  </form>
                </div>
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </body>
</html>

app/templates/login.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Draco | Login</title>
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/login.css') }}"
    />
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
      rel="stylesheet"
    />
    <link
      rel="icon"
      type="image/x-icon"
      href="{{ url_for('static', filename='assets/favico.png') }}"
    />
  </head>
  <body>
    <h2>User Login</h2>
    <div class="login-container">
      <form class="login-form" action="/login" method="POST">
        <div class="input-group">
          <i class="fas fa-envelope"></i>
          <input
            type="email"
            id="email"
            name="email"
            placeholder="Email ID"
            required
          />
        </div>
        <div class="input-group">
          <i class="fas fa-lock"></i>
          <input
            type="password"
            id="password"
            name="password"
            placeholder="Password"
            required
          />
        </div>
        <button type="submit">Login</button>
      </form>
    </div>
    <button class="register-btn" onclick="window.location.href='/register'">
      Register
    </button>
  </body>
</html>

app/templates/register.html
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Draco | Register</title>
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/register.css') }}"
    />
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
      rel="stylesheet"
    />
    <link
      rel="icon"
      type="image/x-icon"
      href="{{ url_for('static', filename='assets/favico.png') }}"
    />
  </head>
  <body>
    <h2>Registrar-se</h2>
    <div class="login-container">
      <form class="login-form" method="POST">
        <div class="input-group">
          <i class="fas fa-user"></i>
          <input
            type="text"
            id="name"
            name="name"
            placeholder="Nome de Usuário"
            required
          />
        </div>
        <div class="input-group">
          <i class="fas fa-envelope"></i>
          <input
            type="email"
            id="email"
            name="email"
            placeholder="Email ID"
            required
          />
        </div>
        <div class="input-group">
          <i class="fas fa-lock"></i>
          <input
            type="password"
            id="password"
            name="password"
            placeholder="Password"
            required
          />
        </div>
        <button type="submit">Registrar</button>
      </form>
    </div>
    <button class="register-btn" onclick="window.location.href='/login'">
      Já tem uma conta? Faça login.
    </button>
  </body>
</html>

app/templates/ver_contas.html
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Draco | Contas</title>
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/ver_contas.css') }}"
    />
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
      rel="stylesheet"
    />
    <link
      rel="icon"
      type="image/x-icon"
      href="{{ url_for('static', filename='assets/favico.png') }}"
    />
  </head>
  <body>
    <div class="container">
      <!-- Card Principal -->
      <div class="main-card">
        <!-- Botão de Voltar -->
        <div class="top-bar">
          <a href="{{ url_for('dashboard') }}" class="btn-voltar">
            <i class="fas fa-arrow-left"></i> Voltar
          </a>
        </div>
        <!-- Saldo Total -->
        <div class="saldo-container">
          <div class="saldo-circle">
            <span>R${{ "{:.2f}".format(saldo_total) }}</span>
          </div>
        </div>
        <hr class="separator" />
        <!-- Lista de Contas -->
        <div class="lista-contas">
          <h3>Minhas Contas</h3>
          <div class="contas-container">
            {% for conta in contas %}
            <div class="conta-card">
              <i class="fas fa-wallet"></i>
              <div class="conta-info">
                <h4>{{ conta.nome }}</h4>
                <a
                  href="{{ url_for('contas.detalhe_conta', user_id=user.id, conta_id=conta.id) }}"
                  class="btn-detalhes"
                  >Ver Detalhes</a
                >
              </div>
            </div>
            {% endfor %}
          </div>
          <!-- Botão Criar Nova Conta -->
          <div class="botao-nova-conta">
            <a
              href="{{ url_for('contas.criar_conta', user_id=user.id) }}"
              class="btn-criar"
            >
              Criar Nova Conta
            </a>
          </div>
        </div>
        <hr class="separator" />
        <!-- Lista de Transações -->
        <h2 class="mb-3">Últimas Transações</h2>
        <table class="table table-bordered">
          <thead>
            <tr>
              <th>Natureza</th>
              <th>Valor (R$)</th>
              <th>Data</th>
              <th>Descrição</th>
              <th>Conta</th>
            </tr>
          </thead>
          <tbody>
            <!-- Exemplo de linha de transação (pode ser substituído com Flask Jinja2) -->
            {% for transacao in transacoes[-5:]|reverse %}
            <tr>
              <td>{{ transacao.natureza }}</td>
              <td>{{ "%.2f"|format(transacao.valor) }}</td>
              <td>{{ transacao.data.strftime('%d/%m/%Y') }}</td>
              <td>{{ transacao.descricao or "N/A" }}</td>
              <td>{{ transacao.conta.nome }}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </body>
</html>

app/templates/ver_perfil.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Draco | Perfil</title>
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/ver_perfil.css') }}"
    />
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
      rel="stylesheet"
    />
    <link
      rel="icon"
      type="image/x-icon"
      href="{{ url_for('static', filename='assets/favico.png') }}"
    />
  </head>
  <body>
    <div class="profile-container">
      <!-- Botão de Voltar -->
      <div class="top-bar">
        <a href="{{ url_for('dashboard') }}" class="btn-voltar">
          <i class="fas fa-arrow-left"></i> Voltar
        </a>
      </div>
      <div class="profile-header">
        <img
          src="{{ url_for('static', filename='assets/draco-logo.jpeg') }}"
          alt="User Photo"
          class="profile-picture"
        />
        <h1>Olá, {{ user.name }}</h1>
      </div>

      <form method="POST" action="/update" class="profile-form">
        <div class="form-row">
          <label for="name">Name</label>
          <input type="text" id="name" name="name" placeholder="Seu nome" />
        </div>

        <div class="form-row">
          <label for="email">Email</label>
          <input type="email" id="email" name="email" placeholder="Seu email" />
        </div>

        <div class="form-row">
          <label for="username">Password</label>
          <input
            type="password"
            id="password"
            name="password"
            placeholder="Senha"
          />
        </div>

        <button type="submit" class="save-button">Salvar</button>
      </form>
      <form action="{{ url_for('delete', user_id=user.id) }}" method="POST">
        <button type="submit" class="delete-btn">Excluir</button>
      </form>
    </div>
  </body>
</html>